export enum Country {
  AUSTRALIA = 'Австралия',
  AUSTRIA = 'Австрия',
  AZERBAIJAN = 'Азербайджан',
  ALBANIA = 'Албания',
  ALGERIA = 'Алжир',
  ANGOLA = 'Ангола',
  ANDORRA = 'Андорра',
  ANTIGUA_AND_BARBUDA = 'Антигуа и Барбуда',
  ARGENTINA = 'Аргентина',
  ARMENIA = 'Армения',
  AFGHANISTAN = 'Афганистан',
  BAHAMAS = 'Багамские Острова',
  BANGLADESH = 'Бангладеш',
  BARBADOS = 'Барбадос',
  BAHRAIN = 'Бахрейн',
  BELARUS = 'Беларусь',
  BELIZE = 'Белиз',
  BELGIUM = 'Бельгия',
  BENIN = 'Бенин',
  BULGARIA = 'Болгария',
  BOLIVIA = 'Боливия',
  BOSNIA_AND_HERZEGOVINA = 'Босния и Герцеговина',
  BOTSWANA = 'Ботсвана',
  BRAZIL = 'Бразилия',
  BRUNEI = 'Бруней',
  BURKINA_FASO = 'Буркина-Фасо',
  BURUNDI = 'Бурунди',
  BHUTAN = 'Бутан',
  VANUATU = 'Вануату',
  UNITED_KINGDOM = 'Великобритания',
  HUNGARY = 'Венгрия',
  VENEZUELA = 'Венесуэла',
  EAST_TIMOR = 'Восточный Тимор',
  VIETNAM = 'Вьетнам',
  GABON = 'Габон',
  HAITI = 'Гаити',
  GUYANA = 'Гайана',
  GAMBIA = 'Гамбия',
  GHANA = 'Гана',
  GUATEMALA = 'Гватемала',
  GUINEA = 'Гвинея',
  GUINEA_BISSAU = 'Гвинея-Бисау',
  GERMANY = 'Германия',
  HONDURAS = 'Гондурас',
  GRENADA = 'Гренада',
  GREECE = 'Греция',
  GEORGIA = 'Грузия',
  DENMARK = 'Дания',
  DJIBOUTI = 'Джибути',
  DOMINICA = 'Доминика',
  DOMINICAN_REPUBLIC = 'Доминиканская Республика',
  EGYPT = 'Египет',
  ZAMBIA = 'Замбия',
  ZIMBABWE = 'Зимбабве',
  ISRAEL = 'Израиль',
  INDIA = 'Индия',
  INDONESIA = 'Индонезия',
  JORDAN = 'Иордания',
  IRAQ = 'Ирак',
  IRAN = 'Иран',
  IRELAND = 'Ирландия',
  ICELAND = 'Исландия',
  SPAIN = 'Испания',
  ITALY = 'Италия',
  YEMEN = 'Йемен',
  CABO_VERDE = 'Кабо-Верде',
  KAZAKHSTAN = 'Казахстан',
  CAMBODIA = 'Камбоджа',
  CAMEROON = 'Камерун',
  CANADA = 'Канада',
  QATAR = 'Катар',
  KENYA = 'Кения',
  CYPRUS = 'Кипр',
  KYRGYZSTAN = 'Кыргызстан',
  KIRIBATI = 'Кирибати',
  CHINA = 'Китай',
  COLOMBIA = 'Колумбия',
  COMOROS = 'Коморы',
  REPUBLIC_OF_CONGO = 'Конго, Республика',
  DEMOCRATIC_REPUBLIC_OF_CONGO = 'Конго, Демократическая Республика',
  COSTA_RICA = 'Коста-Рика',
  COTE_DIVOIRE = "Кот-д'Ивуар",
  CUBA = 'Куба',
  KUWAIT = 'Кувейт',
  LAOS = 'Лаос',
  LATVIA = 'Латвия',
  LESOTHO = 'Лесото',
  LIBERIA = 'Либерия',
  LEBANON = 'Ливан',
  LIBYA = 'Ливия',
  LITHUANIA = 'Литва',
  LIECHTENSTEIN = 'Лихтенштейн',
  LUXEMBOURG = 'Люксембург',
  MAURITIUS = 'Маврикий',
  MAURITANIA = 'Мавритания',
  MADAGASCAR = 'Мадагаскар',
  MALAWI = 'Малави',
  MALAYSIA = 'Малайзия',
  MALI = 'Мали',
  MALDIVES = 'Мальдивы',
  MALTA = 'Мальта',
  MOROCCO = 'Марокко',
  MARSHALL_ISLANDS = 'Маршалловы Острова',
  MEXICO = 'Мексика',
  MICRONESIA = 'Микронезия',
  MOZAMBIQUE = 'Мозамбик',
  MOLDOVA = 'Молдова',
  MONACO = 'Монако',
  MONGOLIA = 'Монголия',
  MYANMAR = 'Мьянма',
  NAMIBIA = 'Намибия',
  NAURU = 'Науру',
  NEPAL = 'Непал',
  NIGER = 'Нигер',
  NIGERIA = 'Нигерия',
  NETHERLANDS = 'Нидерланды',
  NICARAGUA = 'Никарагуа',
  NEW_ZEALAND = 'Новая Зеландия',
  NORWAY = 'Норвегия',
  UNITED_ARAB_EMIRATES = 'Объединённые Арабские Эмираты',
  OMAN = 'Оман',
  PAKISTAN = 'Пакистан',
  PALAU = 'Палау',
  PANAMA = 'Панама',
  PAPUA_NEW_GUINEA = 'Папуа — Новая Гвинея',
  PARAGUAY = 'Парагвай',
  PERU = 'Перу',
  POLAND = 'Польша',
  PORTUGAL = 'Португалия',
  SOUTH_KOREA = 'Республика Корея',
  NORTH_KOREA = 'Северная Корея',
  RUSSIA = 'Россия',
  RWANDA = 'Руанда',
  ROMANIA = 'Румыния',
  EL_SALVADOR = 'Сальвадор',
  SAMOA = 'Самоа',
  SAN_MARINO = 'Сан-Марино',
  SAO_TOME_AND_PRINCIPE = 'Сан-Томе и Принсипи',
  SAUDI_ARABIA = 'Саудовская Аравия',
  NORTH_MACEDONIA = 'Северная Македония',
  SEYCHELLES = 'Сейшельские Острова',
  SENEGAL = 'Сенегал',
  SAINT_VINCENT_AND_THE_GRENADINES = 'Сент-Винсент и Гренадины',
  SAINT_KITTS_AND_NEVIS = 'Сент-Китс и Невис',
  SAINT_LUCIA = 'Сент-Люсия',
  SERBIA = 'Сербия',
  SINGAPORE = 'Сингапур',
  SYRIA = 'Сирия',
  SLOVAKIA = 'Словакия',
  SLOVENIA = 'Словения',
  UNITED_STATES = 'Соединённые Штаты Америки',
  SOLOMON_ISLANDS = 'Соломоновы Острова',
  SOMALIA = 'Сомали',
  SUDAN = 'Судан',
  SURINAME = 'Суринам',
  SIERRA_LEONE = 'Сьерра-Леоне',
  TAJIKISTAN = 'Таджикистан',
  THAILAND = 'Таиланд',
  TANZANIA = 'Танзания',
  TOGO = 'Того',
  TONGA = 'Тонга',
  TRINIDAD_AND_TOBAGO = 'Тринидад и Тобаго',
  TUVALU = 'Тувалу',
  TUNISIA = 'Тунис',
  TURKMENISTAN = 'Туркменистан',
  TURKEY = 'Турция',
  UGANDA = 'Уганда',
  UZBEKISTAN = 'Узбекистан',
  UKRAINE = 'Украина',
  URUGUAY = 'Уругвай',
  FIJI = 'Фиджи',
  PHILIPPINES = 'Филиппины',
  FINLAND = 'Финляндия',
  FRANCE = 'Франция',
  CROATIA = 'Хорватия',
  CENTRAL_AFRICAN_REPUBLIC = 'Центральноафриканская Республика',
  CHAD = 'Чад',
  MONTENEGRO = 'Черногория',
  CZECH_REPUBLIC = 'Чехия',
  CHILE = 'Чили',
  SWITZERLAND = 'Швейцария',
  SWEDEN = 'Швеция',
  SRI_LANKA = 'Шри-Ланка',
  ECUADOR = 'Эквадор',
  EQUATORIAL_GUINEA = 'Экваториальная Гвинея',
  ERITREA = 'Эритрея',
  ESWATINI = 'Эсватини',
  ESTONIA = 'Эстония',
  ETHIOPIA = 'Эфиопия',
  SOUTH_AFRICA = 'Южная Африка',
  SOUTH_SUDAN = 'Южный Судан',
  JAMAICA = 'Ямайка',
  JAPAN = 'Япония',
  GAZE = 'Сектор Газа',
  WESTERN_SAHARA = 'Западная Сахара',
  PALESTINE = 'Палестина',
  KOSOVO = 'Косово',
  FRENCH_GUIANA = 'Французкая Гвиана',
  GIBRALTAR = 'Гибралтар',
  GUAM = 'Гуам',
  MELANESIA = 'Меланезия',
  NEW_CALEDONIA = 'Новая Каледония',
  POLYNESIA = 'Полинезия',
  TAHITI = 'ТАИТИ',
  ISLA_DE_PASCUA = 'Остров пасхи',
}

// Массив всех стран из enum (для обратной совместимости)
export const COUNTRIES: Country[] = Object.values(Country);

export const COUNTRIES_NEIGHTBOURS: Partial<Record<Country, Country[]>> = {
  [Country.TUNISIA]: [Country.LIBYA, Country.ALGERIA],
  [Country.IRAN]: [Country.TURKMENISTAN, Country.AFGHANISTAN, Country.PAKISTAN, Country.KUWAIT, Country.IRAQ, Country.TURKEY, Country.AZERBAIJAN],
  [Country.CUBA]: [],
  [Country.EGYPT]: [Country.LIBYA, Country.SUDAN, Country.GAZE, Country.ISRAEL],
  [Country.SAMOA]: [],
  [Country.ALGERIA]: [Country.TUNISIA, Country.LIBYA, Country.NIGER, Country.MALI, Country.MAURITANIA, Country.MOROCCO],
  [Country.TOGO]: [Country.GHANA, Country.BENIN, Country.BURKINA_FASO],
  [Country.ROMANIA]: [Country.UKRAINE, Country.MOLDOVA, Country.BULGARIA, Country.SERBIA, Country.HUNGARY],
  [Country.JORDAN]: [Country.SYRIA, Country.IRAQ, Country.SAUDI_ARABIA, Country.ISRAEL, Country.PALESTINE],
  [Country.NEW_ZEALAND]: [],
  [Country.SAUDI_ARABIA]: [
    Country.JORDAN,
    Country.IRAQ,
    Country.KUWAIT,
    Country.BAHRAIN,
    Country.QATAR,
    Country.UNITED_ARAB_EMIRATES,
    Country.OMAN,
    Country.YEMEN,
  ],
  [Country.NORTH_MACEDONIA]: [Country.GREECE, Country.ALBANIA, Country.KOSOVO, Country.SERBIA, Country.BULGARIA],
  [Country.ERITREA]: [Country.SUDAN, Country.DJIBOUTI, Country.ETHIOPIA],
  [Country.EL_SALVADOR]: [Country.GUATEMALA, Country.HONDURAS],
  [Country.PERU]: [Country.EQUATORIAL_GUINEA, Country.COLOMBIA, Country.BRAZIL, Country.BOLIVIA, Country.CHILE],
  [Country.MARSHALL_ISLANDS]: [],
  [Country.VENEZUELA]: [Country.COLOMBIA, Country.BRAZIL, Country.GUYANA],
  [Country.LITHUANIA]: [Country.LATVIA, Country.BELARUS, Country.POLAND, Country.RUSSIA],
  [Country.BARBADOS]: [],
  [Country.GHANA]: [Country.COTE_DIVOIRE, Country.BURKINA_FASO, Country.TOGO],
  [Country.BENIN]: [Country.TOGO, Country.BURKINA_FASO, Country.NIGER, Country.NIGERIA],
  [Country.GABON]: [Country.EQUATORIAL_GUINEA, Country.CAMEROON, Country.REPUBLIC_OF_CONGO],
  [Country.COSTA_RICA]: [Country.PANAMA, Country.NICARAGUA],
  [Country.SINGAPORE]: [Country.MALAYSIA],
  [Country.KIRIBATI]: [],
  [Country.LEBANON]: [Country.SYRIA, Country.ISRAEL],
  [Country.NETHERLANDS]: [Country.GERMANY, Country.BELGIUM],
  [Country.BAHRAIN]: [Country.SAUDI_ARABIA, Country.QATAR],
  [Country.JAMAICA]: [],
  [Country.SIERRA_LEONE]: [Country.GUINEA, Country.LIBERIA],
  [Country.SURINAME]: [Country.FRENCH_GUIANA, Country.BRAZIL, Country.GUYANA],
  [Country.NORWAY]: [Country.SWEDEN, Country.FINLAND, Country.RUSSIA],
  [Country.PAKISTAN]: [Country.AFGHANISTAN, Country.CHINA, Country.INDIA, Country.IRAN],
  [Country.TURKMENISTAN]: [Country.KAZAKHSTAN, Country.UZBEKISTAN, Country.AFGHANISTAN, Country.IRAN],
  [Country.VANUATU]: [],
  [Country.ESTONIA]: [Country.RUSSIA, Country.LATVIA],
  [Country.WESTERN_SAHARA]: [Country.MOROCCO, Country.ALGERIA, Country.MAURITANIA],
  [Country.CABO_VERDE]: [],
  [Country.PHILIPPINES]: [],
  [Country.MALDIVES]: [],
  [Country.ANTIGUA_AND_BARBUDA]: [],
  [Country.LUXEMBOURG]: [Country.BELGIUM, Country.GERMANY, Country.FRANCE],
  [Country.CROATIA]: [Country.SLOVENIA, Country.HUNGARY, Country.SERBIA, Country.BOSNIA_AND_HERZEGOVINA, Country.MONTENEGRO],
  [Country.SPAIN]: [Country.FRANCE, Country.PORTUGAL, Country.ANDORRA, Country.GIBRALTAR],
  [Country.ANGOLA]: [Country.REPUBLIC_OF_CONGO, Country.DEMOCRATIC_REPUBLIC_OF_CONGO, Country.ZAMBIA, Country.NAMIBIA],
  [Country.ICELAND]: [],
  [Country.PANAMA]: [Country.COSTA_RICA, Country.COLOMBIA],
  [Country.CANADA]: [Country.UNITED_STATES],
  [Country.THAILAND]: [Country.MYANMAR, Country.LAOS, Country.CAMBODIA, Country.MALAYSIA],
  [Country.TAJIKISTAN]: [Country.UZBEKISTAN, Country.KYRGYZSTAN, Country.CHINA, Country.AFGHANISTAN],
  [Country.SRI_LANKA]: [],
  [Country.HUNGARY]: [Country.SLOVAKIA, Country.UKRAINE, Country.ROMANIA, Country.SERBIA, Country.CROATIA, Country.SLOVENIA, Country.AUSTRIA],
  [Country.AZERBAIJAN]: [Country.RUSSIA, Country.IRAN, Country.ARMENIA, Country.GEORGIA],
  [Country.BHUTAN]: [Country.CHINA, Country.INDIA],
  [Country.INDIA]: [Country.PAKISTAN, Country.CHINA, Country.NEPAL, Country.BHUTAN, Country.BANGLADESH, Country.MYANMAR],
  [Country.UNITED_STATES]: [Country.CANADA, Country.MEXICO],
  [Country.SAINT_VINCENT_AND_THE_GRENADINES]: [],
  [Country.GRENADA]: [Country.GAMBIA, Country.GUINEA],
  [Country.TONGA]: [],
  [Country.BELGIUM]: [Country.NETHERLANDS, Country.GERMANY, Country.LUXEMBOURG, Country.FRANCE],
  [Country.SOUTH_SUDAN]: [
    Country.SUDAN,
    Country.ETHIOPIA,
    Country.KENYA,
    Country.UGANDA,
    Country.DEMOCRATIC_REPUBLIC_OF_CONGO,
    Country.CENTRAL_AFRICAN_REPUBLIC,
  ],
  [Country.JAPAN]: [],
  [Country.DOMINICAN_REPUBLIC]: [Country.HAITI],
  [Country.SAINT_LUCIA]: [],
  [Country.EAST_TIMOR]: [Country.INDONESIA],
  [Country.UKRAINE]: [Country.BELARUS, Country.RUSSIA, Country.ROMANIA, Country.MOLDOVA, Country.ROMANIA, Country.HUNGARY, Country.SLOVAKIA, Country.POLAND],
  [Country.FIJI]: [],
  [Country.MICRONESIA]: [Country.PALAU, Country.GUAM],
  [Country.MELANESIA]: [Country.PAPUA_NEW_GUINEA, Country.FIJI, Country.NEW_CALEDONIA],
  [Country.POLYNESIA]: [Country.TAHITI, Country.ISLA_DE_PASCUA],
  [Country.BELIZE]: [Country.GUATEMALA, Country.MEXICO],
  [Country.MYANMAR]: [Country.CHINA, Country.LAOS, Country.THAILAND, Country.BHUTAN, Country.INDIA, Country.BANGLADESH],
  [Country.MAURITIUS]: [],
  [Country.ISRAEL]: [Country.LEBANON, Country.SYRIA, Country.JORDAN, Country.EGYPT],
  [Country.SOUTH_KOREA]: [Country.NORTH_KOREA],
  [Country.REPUBLIC_OF_CONGO]: [Country.CENTRAL_AFRICAN_REPUBLIC, Country.DEMOCRATIC_REPUBLIC_OF_CONGO, Country.GABON, Country.CAMEROON],
  [Country.NORTH_KOREA]: [Country.CHINA, Country.RUSSIA, Country.SOUTH_KOREA],
  [Country.BOLIVIA]: [Country.BRAZIL, Country.PARAGUAY, Country.ARGENTINA, Country.CHILE, Country.PERU],
  [Country.COLOMBIA]: [Country.PANAMA, Country.VENEZUELA, Country.BRAZIL, Country.PERU, Country.ECUADOR],
  [Country.OMAN]: [Country.UNITED_ARAB_EMIRATES, Country.SAUDI_ARABIA, Country.YEMEN],
  [Country.CZECH_REPUBLIC]: [Country.POLAND, Country.SLOVAKIA, Country.AUSTRIA, Country.GERMANY],
  [Country.LIBYA]: [Country.EGYPT, Country.SUDAN, Country.CHAD, Country.NIGER, Country.ALGERIA, Country.TUNISIA],
  [Country.CAMEROON]: [Country.NIGERIA, Country.CHAD, Country.CENTRAL_AFRICAN_REPUBLIC, Country.REPUBLIC_OF_CONGO, Country.GABON, Country.EQUATORIAL_GUINEA],
  [Country.UNITED_ARAB_EMIRATES]: [Country.OMAN, Country.SAUDI_ARABIA],
  [Country.SLOVAKIA]: [Country.POLAND, Country.UKRAINE, Country.HUNGARY, Country.AUSTRIA, Country.CZECH_REPUBLIC],
  [Country.GUATEMALA]: [Country.BELIZE, Country.HONDURAS, Country.EL_SALVADOR, Country.MEXICO],
  [Country.FINLAND]: [Country.SWEDEN, Country.NORWAY, Country.RUSSIA],
  [Country.FRENCH_GUIANA]: [Country.SURINAME, Country.BRAZIL],
  [Country.ECUADOR]: [Country.COLOMBIA, Country.PERU],
  [Country.GIBRALTAR]: [Country.GIBRALTAR],
  [Country.SYRIA]: [Country.TURKEY, Country.IRAQ, Country.JORDAN, Country.LEBANON, Country.ISRAEL],
  [Country.COTE_DIVOIRE]: [Country.MALI, Country.BURKINA_FASO, Country.GHANA, Country.LIBERIA, Country.GUINEA],
  [Country.CHAD]: [Country.SUDAN, Country.CENTRAL_AFRICAN_REPUBLIC, Country.CAMEROON, Country.NIGERIA, Country.NIGER, Country.LIBYA],
  [Country.COMOROS]: [],
  [Country.MOLDOVA]: [Country.UKRAINE, Country.ROMANIA],
  [Country.KUWAIT]: [Country.IRAQ, Country.SAUDI_ARABIA],
  [Country.TUVALU]: [],
  [Country.BOTSWANA]: [Country.ZAMBIA, Country.ZIMBABWE, Country.SOUTH_AFRICA, Country.NAMIBIA],
  [Country.AUSTRALIA]: [],
  [Country.AUSTRIA]: [Country.CZECH_REPUBLIC, Country.SLOVAKIA, Country.HUNGARY, Country.SLOVENIA, Country.ITALY, Country.SWITZERLAND, Country.GERMANY],
  [Country.ALBANIA]: [Country.MONTENEGRO, Country.KOSOVO, Country.NORTH_MACEDONIA, Country.GREECE],
  [Country.ANDORRA]: [Country.FRANCE, Country.SPAIN],
  [Country.ARGENTINA]: [Country.CHILE, Country.BOLIVIA, Country.PARAGUAY, Country.URUGUAY, Country.BRAZIL],
  [Country.ARMENIA]: [Country.GEORGIA, Country.AZERBAIJAN, Country.IRAN, Country.TURKEY],
};

// Написать скрипт для проверки, что б все страны взаимно друг друга включали и ничего не упустил
// Игра в угадать направление!
// Сделать так, что б свопросом ещё видел и флаг
// Как пишутся на англ
// Страны на одну букву
// 10 крупных стран, самые крупные страны по континентам
