export enum Country {
  AUSTRALIA = 'Австралия',
  AUSTRIA = 'Австрия',
  AZERBAIJAN = 'Азербайджан',
  ALBANIA = 'Албания',
  ALGERIA = 'Алжир',
  ANGOLA = 'Ангола',
  ANDORRA = 'Андорра',
  ANTIGUA_AND_BARBUDA = 'Антигуа и Барбуда',
  ARGENTINA = 'Аргентина',
  ARMENIA = 'Армения',
  AFGHANISTAN = 'Афганистан',
  BAHAMAS = 'Багамские Острова',
  BANGLADESH = 'Бангладеш',
  BARBADOS = 'Барбадос',
  BAHRAIN = 'Бахрейн',
  BELARUS = 'Беларусь',
  BELIZE = 'Белиз',
  BELGIUM = 'Бельгия',
  BENIN = 'Бенин',
  BULGARIA = 'Болгария',
  BOLIVIA = 'Боливия',
  BOSNIA_AND_HERZEGOVINA = 'Босния и Герцеговина',
  BOTSWANA = 'Ботсвана',
  BRAZIL = 'Бразилия',
  BRUNEI = 'Бруней',
  BURKINA_FASO = 'Буркина-Фасо',
  BURUNDI = 'Бурунди',
  BHUTAN = 'Бутан',
  VANUATU = 'Вануату',
  UNITED_KINGDOM = 'Великобритания',
  HUNGARY = 'Венгрия',
  VENEZUELA = 'Венесуэла',
  EAST_TIMOR = 'Восточный Тимор',
  VIETNAM = 'Вьетнам',
  GABON = 'Габон',
  HAITI = 'Гаити',
  GUYANA = 'Гайана',
  GAMBIA = 'Гамбия',
  GHANA = 'Гана',
  GUATEMALA = 'Гватемала',
  GUINEA = 'Гвинея',
  GUINEA_BISSAU = 'Гвинея-Бисау',
  GERMANY = 'Германия',
  HONDURAS = 'Гондурас',
  GRENADA = 'Гренада',
  GREECE = 'Греция',
  GEORGIA = 'Грузия',
  DENMARK = 'Дания',
  DJIBOUTI = 'Джибути',
  DOMINICA = 'Доминика',
  DOMINICAN_REPUBLIC = 'Доминиканская Республика',
  EGYPT = 'Египет',
  ZAMBIA = 'Замбия',
  ZIMBABWE = 'Зимбабве',
  ISRAEL = 'Израиль',
  INDIA = 'Индия',
  INDONESIA = 'Индонезия',
  JORDAN = 'Иордания',
  IRAQ = 'Ирак',
  IRAN = 'Иран',
  IRELAND = 'Ирландия',
  ICELAND = 'Исландия',
  SPAIN = 'Испания',
  ITALY = 'Италия',
  YEMEN = 'Йемен',
  CABO_VERDE = 'Кабо-Верде',
  KAZAKHSTAN = 'Казахстан',
  CAMBODIA = 'Камбоджа',
  CAMEROON = 'Камерун',
  CANADA = 'Канада',
  QATAR = 'Катар',
  KENYA = 'Кения',
  CYPRUS = 'Кипр',
  KYRGYZSTAN = 'Кыргызстан',
  KIRIBATI = 'Кирибати',
  CHINA = 'Китай',
  COLOMBIA = 'Колумбия',
  COMOROS = 'Коморы',
  REPUBLIC_OF_CONGO = 'Конго, Республика',
  DEMOCRATIC_REPUBLIC_OF_CONGO = 'Конго, Демократическая Республика',
  COSTA_RICA = 'Коста-Рика',
  COTE_DIVOIRE = "Кот-д'Ивуар",
  CUBA = 'Куба',
  KUWAIT = 'Кувейт',
  LAOS = 'Лаос',
  LATVIA = 'Латвия',
  LESOTHO = 'Лесото',
  LIBERIA = 'Либерия',
  LEBANON = 'Ливан',
  LIBYA = 'Ливия',
  LITHUANIA = 'Литва',
  LIECHTENSTEIN = 'Лихтенштейн',
  LUXEMBOURG = 'Люксембург',
  MAURITIUS = 'Маврикий',
  MAURITANIA = 'Мавритания',
  MADAGASCAR = 'Мадагаскар',
  MALAWI = 'Малави',
  MALAYSIA = 'Малайзия',
  MALI = 'Мали',
  MALDIVES = 'Мальдивы',
  MALTA = 'Мальта',
  MOROCCO = 'Марокко',
  MARSHALL_ISLANDS = 'Маршалловы Острова',
  MEXICO = 'Мексика',
  MICRONESIA = 'Микронезия',
  MOZAMBIQUE = 'Мозамбик',
  MOLDOVA = 'Молдова',
  MONACO = 'Монако',
  MONGOLIA = 'Монголия',
  MYANMAR = 'Мьянма',
  NAMIBIA = 'Намибия',
  NAURU = 'Науру',
  NEPAL = 'Непал',
  NIGER = 'Нигер',
  NIGERIA = 'Нигерия',
  NETHERLANDS = 'Нидерланды',
  NICARAGUA = 'Никарагуа',
  NEW_ZEALAND = 'Новая Зеландия',
  NORWAY = 'Норвегия',
  UNITED_ARAB_EMIRATES = 'Объединённые Арабские Эмираты',
  OMAN = 'Оман',
  PAKISTAN = 'Пакистан',
  PALAU = 'Палау',
  PANAMA = 'Панама',
  PAPUA_NEW_GUINEA = 'Папуа — Новая Гвинея',
  PARAGUAY = 'Парагвай',
  PERU = 'Перу',
  POLAND = 'Польша',
  PORTUGAL = 'Португалия',
  SOUTH_KOREA = 'Республика Корея',
  NORTH_KOREA = 'Северная Корея',
  RUSSIA = 'Россия',
  RWANDA = 'Руанда',
  ROMANIA = 'Румыния',
  EL_SALVADOR = 'Сальвадор',
  SAMOA = 'Самоа',
  SAN_MARINO = 'Сан-Марино',
  SAO_TOME_AND_PRINCIPE = 'Сан-Томе и Принсипи',
  SAUDI_ARABIA = 'Саудовская Аравия',
  NORTH_MACEDONIA = 'Северная Македония',
  SEYCHELLES = 'Сейшельские Острова',
  SENEGAL = 'Сенегал',
  SAINT_VINCENT_AND_THE_GRENADINES = 'Сент-Винсент и Гренадины',
  SAINT_KITTS_AND_NEVIS = 'Сент-Китс и Невис',
  SAINT_LUCIA = 'Сент-Люсия',
  SERBIA = 'Сербия',
  SINGAPORE = 'Сингапур',
  SYRIA = 'Сирия',
  SLOVAKIA = 'Словакия',
  SLOVENIA = 'Словения',
  UNITED_STATES = 'Соединённые Штаты Америки',
  SOLOMON_ISLANDS = 'Соломоновы Острова',
  SOMALIA = 'Сомали',
  SUDAN = 'Судан',
  SURINAME = 'Суринам',
  SIERRA_LEONE = 'Сьерра-Леоне',
  TAJIKISTAN = 'Таджикистан',
  THAILAND = 'Таиланд',
  TANZANIA = 'Танзания',
  TOGO = 'Того',
  TONGA = 'Тонга',
  TRINIDAD_AND_TOBAGO = 'Тринидад и Тобаго',
  TUVALU = 'Тувалу',
  TUNISIA = 'Тунис',
  TURKMENISTAN = 'Туркменистан',
  TURKEY = 'Турция',
  UGANDA = 'Уганда',
  UZBEKISTAN = 'Узбекистан',
  UKRAINE = 'Украина',
  URUGUAY = 'Уругвай',
  FIJI = 'Фиджи',
  PHILIPPINES = 'Филиппины',
  FINLAND = 'Финляндия',
  FRANCE = 'Франция',
  CROATIA = 'Хорватия',
  CENTRAL_AFRICAN_REPUBLIC = 'Центральноафриканская Республика',
  CHAD = 'Чад',
  MONTENEGRO = 'Черногория',
  CZECHIA = 'Чехия',
  CHILE = 'Чили',
  SWITZERLAND = 'Швейцария',
  SWEDEN = 'Швеция',
  SRI_LANKA = 'Шри-Ланка',
  ECUADOR = 'Эквадор',
  EQUATORIAL_GUINEA = 'Экваториальная Гвинея',
  ERITREA = 'Эритрея',
  ESWATINI = 'Эсватини',
  ESTONIA = 'Эстония',
  ETHIOPIA = 'Эфиопия',
  SOUTH_AFRICA = 'Южная Африка',
  SOUTH_SUDAN = 'Южный Судан',
  JAMAICA = 'Ямайка',
  JAPAN = 'Япония',
  GAZE = 'Сектор Газа',
  WESTERN_SAHARA = 'Западная Сахара',
  PALESTINE = 'Палестина',
  KOSOVO = 'Косово',
  FRENCH_GUIANA = 'Французкая Гвиана',
  GIBRALTAR = 'Гибралтар',
  GUAM = 'Гуам',
  NEW_CALEDONIA = 'Новая Каледония',
  POLYNESIA = 'Полинезия',
  TAHITI = 'Таити',
  ISLA_DE_PASCUA = 'Остров пасхи',
}

// Массив всех стран из enum (для обратной совместимости)
export const COUNTRIES: Country[] = Object.values(Country);

export const COUNTRIES_NEIGHTBOURS: Partial<Record<Country, Country[]>> = {
  [Country.TUNISIA]: [Country.LIBYA, Country.ALGERIA],
  [Country.IRAN]: [Country.TURKMENISTAN, Country.AFGHANISTAN, Country.PAKISTAN, Country.IRAQ, Country.TURKEY, Country.AZERBAIJAN, Country.ARMENIA],
  [Country.CUBA]: [],
  [Country.EGYPT]: [Country.LIBYA, Country.SUDAN, Country.GAZE, Country.ISRAEL],
  [Country.SAMOA]: [],
  [Country.ALGERIA]: [Country.TUNISIA, Country.LIBYA, Country.NIGER, Country.MALI, Country.MAURITANIA, Country.MOROCCO, Country.WESTERN_SAHARA],
  [Country.TOGO]: [Country.GHANA, Country.BENIN, Country.BURKINA_FASO],
  [Country.ROMANIA]: [Country.UKRAINE, Country.MOLDOVA, Country.BULGARIA, Country.SERBIA, Country.HUNGARY],
  [Country.JORDAN]: [Country.SYRIA, Country.IRAQ, Country.SAUDI_ARABIA, Country.ISRAEL, Country.PALESTINE],
  [Country.NEW_ZEALAND]: [],
  [Country.SAUDI_ARABIA]: [
    Country.JORDAN,
    Country.IRAQ,
    Country.KUWAIT,
    Country.BAHRAIN,
    Country.QATAR,
    Country.UNITED_ARAB_EMIRATES,
    Country.OMAN,
    Country.YEMEN,
  ],
  [Country.NORTH_MACEDONIA]: [Country.GREECE, Country.ALBANIA, Country.KOSOVO, Country.SERBIA, Country.BULGARIA],
  [Country.ERITREA]: [Country.SUDAN, Country.DJIBOUTI, Country.ETHIOPIA],
  [Country.EL_SALVADOR]: [Country.GUATEMALA, Country.HONDURAS],
  [Country.PERU]: [Country.ECUADOR, Country.COLOMBIA, Country.BRAZIL, Country.BOLIVIA, Country.CHILE],
  [Country.MARSHALL_ISLANDS]: [],
  [Country.VENEZUELA]: [Country.COLOMBIA, Country.BRAZIL, Country.GUYANA],
  [Country.LITHUANIA]: [Country.LATVIA, Country.BELARUS, Country.POLAND, Country.RUSSIA],
  [Country.BARBADOS]: [],
  [Country.GHANA]: [Country.COTE_DIVOIRE, Country.BURKINA_FASO, Country.TOGO],
  [Country.BENIN]: [Country.TOGO, Country.BURKINA_FASO, Country.NIGER, Country.NIGERIA],
  [Country.GABON]: [Country.EQUATORIAL_GUINEA, Country.CAMEROON, Country.REPUBLIC_OF_CONGO],
  [Country.COSTA_RICA]: [Country.PANAMA, Country.NICARAGUA],
  [Country.SINGAPORE]: [Country.MALAYSIA],
  [Country.KIRIBATI]: [],
  [Country.LEBANON]: [Country.SYRIA, Country.ISRAEL],
  [Country.NETHERLANDS]: [Country.GERMANY, Country.BELGIUM],
  [Country.BAHRAIN]: [Country.SAUDI_ARABIA],
  [Country.JAMAICA]: [],
  [Country.SIERRA_LEONE]: [Country.GUINEA, Country.LIBERIA],
  [Country.SURINAME]: [Country.FRENCH_GUIANA, Country.BRAZIL, Country.GUYANA],
  [Country.NORWAY]: [Country.SWEDEN, Country.FINLAND, Country.RUSSIA],
  [Country.PAKISTAN]: [Country.AFGHANISTAN, Country.CHINA, Country.INDIA, Country.IRAN],
  [Country.TURKMENISTAN]: [Country.KAZAKHSTAN, Country.UZBEKISTAN, Country.AFGHANISTAN, Country.IRAN],
  [Country.VANUATU]: [],
  [Country.ESTONIA]: [Country.RUSSIA, Country.LATVIA],
  [Country.WESTERN_SAHARA]: [Country.MOROCCO, Country.ALGERIA, Country.MAURITANIA],
  [Country.CABO_VERDE]: [],
  [Country.PHILIPPINES]: [],
  [Country.MALDIVES]: [],
  [Country.ANTIGUA_AND_BARBUDA]: [],
  [Country.LUXEMBOURG]: [Country.BELGIUM, Country.GERMANY, Country.FRANCE],
  [Country.CROATIA]: [Country.SLOVENIA, Country.HUNGARY, Country.SERBIA, Country.BOSNIA_AND_HERZEGOVINA, Country.MONTENEGRO],
  [Country.SPAIN]: [Country.FRANCE, Country.PORTUGAL, Country.ANDORRA, Country.GIBRALTAR],
  [Country.ANGOLA]: [Country.DEMOCRATIC_REPUBLIC_OF_CONGO, Country.ZAMBIA, Country.NAMIBIA],
  [Country.ICELAND]: [],
  [Country.PANAMA]: [Country.COSTA_RICA, Country.COLOMBIA],
  [Country.CANADA]: [Country.UNITED_STATES],
  [Country.THAILAND]: [Country.MYANMAR, Country.LAOS, Country.CAMBODIA, Country.MALAYSIA],
  [Country.TAJIKISTAN]: [Country.UZBEKISTAN, Country.KYRGYZSTAN, Country.CHINA, Country.AFGHANISTAN],
  [Country.SRI_LANKA]: [],
  [Country.HUNGARY]: [Country.SLOVAKIA, Country.UKRAINE, Country.ROMANIA, Country.SERBIA, Country.CROATIA, Country.SLOVENIA, Country.AUSTRIA],
  [Country.AZERBAIJAN]: [Country.RUSSIA, Country.IRAN, Country.ARMENIA, Country.GEORGIA],
  [Country.BHUTAN]: [Country.CHINA, Country.INDIA],
  [Country.INDIA]: [Country.PAKISTAN, Country.CHINA, Country.NEPAL, Country.BHUTAN, Country.BANGLADESH, Country.MYANMAR],
  [Country.UNITED_STATES]: [Country.CANADA, Country.MEXICO, Country.RUSSIA],
  [Country.SAINT_VINCENT_AND_THE_GRENADINES]: [],
  [Country.GRENADA]: [],
  [Country.TONGA]: [],
  [Country.BELGIUM]: [Country.NETHERLANDS, Country.GERMANY, Country.LUXEMBOURG, Country.FRANCE],
  [Country.SOUTH_SUDAN]: [
    Country.SUDAN,
    Country.ETHIOPIA,
    Country.KENYA,
    Country.UGANDA,
    Country.DEMOCRATIC_REPUBLIC_OF_CONGO,
    Country.CENTRAL_AFRICAN_REPUBLIC,
  ],
  [Country.JAPAN]: [],
  [Country.DOMINICAN_REPUBLIC]: [Country.HAITI],
  [Country.SAINT_LUCIA]: [],
  [Country.EAST_TIMOR]: [Country.INDONESIA],
  [Country.UKRAINE]: [Country.BELARUS, Country.RUSSIA, Country.ROMANIA, Country.MOLDOVA, Country.ROMANIA, Country.HUNGARY, Country.SLOVAKIA, Country.POLAND],
  [Country.FIJI]: [],
  [Country.MICRONESIA]: [],
  [Country.POLYNESIA]: [Country.TAHITI, Country.ISLA_DE_PASCUA],
  [Country.BELIZE]: [Country.GUATEMALA, Country.MEXICO],
  [Country.MYANMAR]: [Country.CHINA, Country.LAOS, Country.THAILAND, Country.INDIA, Country.BANGLADESH],
  [Country.MAURITIUS]: [],
  [Country.ISRAEL]: [Country.LEBANON, Country.SYRIA, Country.JORDAN, Country.EGYPT, Country.PALESTINE, Country.GAZE],
  [Country.SOUTH_KOREA]: [Country.NORTH_KOREA],
  [Country.REPUBLIC_OF_CONGO]: [Country.CENTRAL_AFRICAN_REPUBLIC, Country.DEMOCRATIC_REPUBLIC_OF_CONGO, Country.GABON, Country.CAMEROON],
  [Country.NORTH_KOREA]: [Country.CHINA, Country.RUSSIA, Country.SOUTH_KOREA],
  [Country.BOLIVIA]: [Country.BRAZIL, Country.PARAGUAY, Country.ARGENTINA, Country.CHILE, Country.PERU],
  [Country.COLOMBIA]: [Country.PANAMA, Country.VENEZUELA, Country.BRAZIL, Country.PERU, Country.ECUADOR],
  [Country.OMAN]: [Country.UNITED_ARAB_EMIRATES, Country.SAUDI_ARABIA, Country.YEMEN],
  [Country.CZECHIA]: [Country.POLAND, Country.SLOVAKIA, Country.AUSTRIA, Country.GERMANY],
  [Country.LIBYA]: [Country.EGYPT, Country.SUDAN, Country.CHAD, Country.NIGER, Country.ALGERIA, Country.TUNISIA],
  [Country.CAMEROON]: [Country.NIGERIA, Country.CHAD, Country.CENTRAL_AFRICAN_REPUBLIC, Country.REPUBLIC_OF_CONGO, Country.GABON, Country.EQUATORIAL_GUINEA],
  [Country.UNITED_ARAB_EMIRATES]: [Country.OMAN, Country.SAUDI_ARABIA],
  [Country.SLOVAKIA]: [Country.POLAND, Country.UKRAINE, Country.HUNGARY, Country.AUSTRIA, Country.CZECHIA],
  [Country.GUATEMALA]: [Country.BELIZE, Country.HONDURAS, Country.EL_SALVADOR, Country.MEXICO],
  [Country.FINLAND]: [Country.SWEDEN, Country.NORWAY, Country.RUSSIA],
  [Country.FRENCH_GUIANA]: [Country.SURINAME, Country.BRAZIL],
  [Country.ECUADOR]: [Country.COLOMBIA, Country.PERU],
  [Country.GIBRALTAR]: [Country.SPAIN],
  [Country.SYRIA]: [Country.TURKEY, Country.IRAQ, Country.JORDAN, Country.LEBANON, Country.ISRAEL],
  [Country.COTE_DIVOIRE]: [Country.MALI, Country.BURKINA_FASO, Country.GHANA, Country.LIBERIA, Country.GUINEA],
  [Country.CHAD]: [Country.SUDAN, Country.CENTRAL_AFRICAN_REPUBLIC, Country.CAMEROON, Country.NIGERIA, Country.NIGER, Country.LIBYA],
  [Country.COMOROS]: [],
  [Country.MOLDOVA]: [Country.UKRAINE, Country.ROMANIA],
  [Country.KUWAIT]: [Country.IRAQ, Country.SAUDI_ARABIA],
  [Country.TUVALU]: [],
  [Country.BOTSWANA]: [Country.ZAMBIA, Country.ZIMBABWE, Country.SOUTH_AFRICA, Country.NAMIBIA],
  [Country.AUSTRALIA]: [],
  [Country.AUSTRIA]: [
    Country.CZECHIA,
    Country.SLOVAKIA,
    Country.HUNGARY,
    Country.SLOVENIA,
    Country.ITALY,
    Country.SWITZERLAND,
    Country.GERMANY,
    Country.LIECHTENSTEIN,
  ],
  [Country.ALBANIA]: [Country.MONTENEGRO, Country.KOSOVO, Country.NORTH_MACEDONIA, Country.GREECE],
  [Country.ANDORRA]: [Country.FRANCE, Country.SPAIN],
  [Country.ARGENTINA]: [Country.CHILE, Country.BOLIVIA, Country.PARAGUAY, Country.URUGUAY, Country.BRAZIL],
  [Country.ARMENIA]: [Country.GEORGIA, Country.AZERBAIJAN, Country.IRAN, Country.TURKEY],
  [Country.AFGHANISTAN]: [Country.UZBEKISTAN, Country.TAJIKISTAN, Country.PAKISTAN, Country.IRAN, Country.TURKMENISTAN, Country.CHINA],
  [Country.BAHAMAS]: [],
  [Country.BANGLADESH]: [Country.INDIA, Country.MYANMAR],
  [Country.BELARUS]: [Country.RUSSIA, Country.UKRAINE, Country.POLAND, Country.LITHUANIA, Country.LATVIA],
  [Country.BULGARIA]: [Country.ROMANIA, Country.TURKEY, Country.GREECE, Country.NORTH_MACEDONIA, Country.SERBIA],
  [Country.BOSNIA_AND_HERZEGOVINA]: [Country.CROATIA, Country.SERBIA, Country.MONTENEGRO],
  [Country.BRAZIL]: [
    Country.URUGUAY,
    Country.ARGENTINA,
    Country.PARAGUAY,
    Country.BOLIVIA,
    Country.PERU,
    Country.COLOMBIA,
    Country.VENEZUELA,
    Country.GUYANA,
    Country.SURINAME,
    Country.FRENCH_GUIANA,
  ],
  [Country.BRUNEI]: [Country.MALAYSIA],
  [Country.BURKINA_FASO]: [Country.MALI, Country.NIGER, Country.BENIN, Country.TOGO, Country.GHANA, Country.COTE_DIVOIRE],
  [Country.BURUNDI]: [Country.RWANDA, Country.TANZANIA, Country.DEMOCRATIC_REPUBLIC_OF_CONGO],
  [Country.UNITED_KINGDOM]: [Country.IRELAND],
  [Country.VIETNAM]: [Country.CHINA, Country.CAMBODIA, Country.LAOS],
  [Country.HAITI]: [Country.DOMINICAN_REPUBLIC],
  [Country.GUYANA]: [Country.BRAZIL, Country.VENEZUELA, Country.SURINAME],
  [Country.GAMBIA]: [Country.SENEGAL],
  [Country.GUINEA]: [Country.GUINEA_BISSAU, Country.SIERRA_LEONE, Country.LIBERIA, Country.COTE_DIVOIRE, Country.SENEGAL, Country.MALI],
  [Country.GUINEA_BISSAU]: [Country.SENEGAL, Country.GUINEA],
  [Country.GERMANY]: [
    Country.DENMARK,
    Country.POLAND,
    Country.CZECHIA,
    Country.AUSTRIA,
    Country.SWITZERLAND,
    Country.FRANCE,
    Country.LUXEMBOURG,
    Country.BELGIUM,
    Country.NETHERLANDS,
  ],
  [Country.HONDURAS]: [Country.NICARAGUA, Country.EL_SALVADOR, Country.GUATEMALA],
  [Country.GREECE]: [Country.ALBANIA, Country.NORTH_MACEDONIA, Country.BULGARIA, Country.TURKEY],
  [Country.GEORGIA]: [Country.RUSSIA, Country.AZERBAIJAN, Country.TURKEY, Country.ARMENIA],
  [Country.DENMARK]: [Country.GERMANY],
  [Country.DJIBOUTI]: [Country.ETHIOPIA, Country.ERITREA, Country.SOMALIA],
  [Country.DOMINICA]: [],
  [Country.ZAMBIA]: [
    Country.DEMOCRATIC_REPUBLIC_OF_CONGO,
    Country.TANZANIA,
    Country.MALAWI,
    Country.MOZAMBIQUE,
    Country.ZIMBABWE,
    Country.BOTSWANA,
    Country.NAMIBIA,
    Country.ANGOLA,
  ],
  [Country.ZIMBABWE]: [Country.ZAMBIA, Country.MOZAMBIQUE, Country.SOUTH_AFRICA, Country.BOTSWANA, Country.NAMIBIA],
  [Country.INDONESIA]: [Country.PAPUA_NEW_GUINEA, Country.MALAYSIA, Country.EAST_TIMOR],
  [Country.IRAQ]: [Country.TURKEY, Country.IRAN, Country.SYRIA, Country.KUWAIT, Country.JORDAN, Country.SAUDI_ARABIA],
  [Country.IRELAND]: [Country.UNITED_KINGDOM],
  [Country.ITALY]: [Country.FRANCE, Country.SWITZERLAND, Country.AUSTRIA, Country.SLOVENIA, Country.SAN_MARINO],
  [Country.YEMEN]: [Country.SAUDI_ARABIA, Country.OMAN],
  [Country.KAZAKHSTAN]: [Country.RUSSIA, Country.UZBEKISTAN, Country.KYRGYZSTAN, Country.CHINA, Country.TURKMENISTAN],
  [Country.CAMBODIA]: [Country.THAILAND, Country.LAOS, Country.VIETNAM],
  [Country.QATAR]: [Country.SAUDI_ARABIA],
  [Country.KENYA]: [Country.ETHIOPIA, Country.SOMALIA, Country.UGANDA, Country.SOUTH_SUDAN, Country.TANZANIA],
  [Country.SOMALIA]: [Country.DJIBOUTI, Country.ETHIOPIA, Country.KENYA],
  [Country.CYPRUS]: [],
  [Country.KYRGYZSTAN]: [Country.KAZAKHSTAN, Country.CHINA, Country.UZBEKISTAN, Country.TAJIKISTAN],
  [Country.CHINA]: [
    Country.RUSSIA,
    Country.MONGOLIA,
    Country.NORTH_KOREA,
    Country.VIETNAM,
    Country.LAOS,
    Country.MYANMAR,
    Country.INDIA,
    Country.BHUTAN,
    Country.NEPAL,
    Country.PAKISTAN,
    Country.AFGHANISTAN,
    Country.TAJIKISTAN,
    Country.KYRGYZSTAN,
    Country.KAZAKHSTAN,
  ],
  [Country.DEMOCRATIC_REPUBLIC_OF_CONGO]: [
    Country.CENTRAL_AFRICAN_REPUBLIC,
    Country.SOUTH_SUDAN,
    Country.UGANDA,
    Country.RWANDA,
    Country.BURUNDI,
    Country.TANZANIA,
    Country.ZAMBIA,
    Country.ANGOLA,
    Country.REPUBLIC_OF_CONGO,
  ],
  [Country.LAOS]: [Country.CHINA, Country.VIETNAM, Country.CAMBODIA, Country.THAILAND, Country.MYANMAR],
  [Country.LATVIA]: [Country.ESTONIA, Country.RUSSIA, Country.BELARUS, Country.LITHUANIA],
  [Country.LESOTHO]: [Country.SOUTH_AFRICA],
  [Country.LIBERIA]: [Country.SIERRA_LEONE, Country.GUINEA, Country.COTE_DIVOIRE],
  [Country.LIECHTENSTEIN]: [Country.SWITZERLAND, Country.AUSTRIA],
  [Country.MAURITANIA]: [Country.WESTERN_SAHARA, Country.ALGERIA, Country.MALI, Country.SENEGAL],
  [Country.MADAGASCAR]: [],
  [Country.MALAWI]: [Country.TANZANIA, Country.MOZAMBIQUE, Country.ZAMBIA],
  [Country.MALAYSIA]: [Country.THAILAND, Country.INDONESIA, Country.SINGAPORE, Country.BRUNEI],
  [Country.MALI]: [Country.ALGERIA, Country.NIGER, Country.BURKINA_FASO, Country.COTE_DIVOIRE, Country.GUINEA, Country.SENEGAL, Country.MAURITANIA],
  [Country.MALTA]: [],
  [Country.MOROCCO]: [Country.ALGERIA, Country.WESTERN_SAHARA],
  [Country.MEXICO]: [Country.UNITED_STATES, Country.GUATEMALA, Country.BELIZE],
  [Country.MOZAMBIQUE]: [Country.TANZANIA, Country.MALAWI, Country.ZAMBIA, Country.ZIMBABWE, Country.ESWATINI, Country.SOUTH_AFRICA],
  [Country.ESWATINI]: [Country.MOZAMBIQUE, Country.SOUTH_AFRICA],
  [Country.MONACO]: [Country.FRANCE],
  [Country.MONGOLIA]: [Country.RUSSIA, Country.CHINA],
  [Country.NAMIBIA]: [Country.ANGOLA, Country.ZAMBIA, Country.ZIMBABWE, Country.BOTSWANA, Country.SOUTH_AFRICA],
  [Country.NAURU]: [],
  [Country.NEPAL]: [Country.INDIA, Country.CHINA],
  [Country.NIGERIA]: [Country.BENIN, Country.NIGER, Country.CHAD, Country.CAMEROON],
  [Country.NIGER]: [Country.NIGERIA, Country.BENIN, Country.BURKINA_FASO, Country.MALI, Country.ALGERIA, Country.LIBYA, Country.CHAD],
  [Country.NICARAGUA]: [Country.HONDURAS, Country.COSTA_RICA],
  [Country.PALAU]: [],
  [Country.PAPUA_NEW_GUINEA]: [Country.INDONESIA],
  [Country.PARAGUAY]: [Country.BOLIVIA, Country.BRAZIL, Country.ARGENTINA],
  [Country.POLAND]: [Country.BELARUS, Country.UKRAINE, Country.RUSSIA, Country.LITHUANIA, Country.SLOVAKIA, Country.CZECHIA, Country.GERMANY],
  [Country.PORTUGAL]: [Country.SPAIN],
  [Country.RUSSIA]: [
    Country.NORWAY,
    Country.BELARUS,
    Country.LATVIA,
    Country.ESTONIA,
    Country.FINLAND,
    Country.UNITED_STATES,
    Country.NORTH_KOREA,
    Country.CHINA,
    Country.MONGOLIA,
    Country.KAZAKHSTAN,
    Country.GEORGIA,
    Country.AZERBAIJAN,
    Country.UKRAINE,
    Country.POLAND,
    Country.LITHUANIA,
  ],
  [Country.RWANDA]: [Country.BURUNDI, Country.TANZANIA, Country.DEMOCRATIC_REPUBLIC_OF_CONGO, Country.UGANDA],
  [Country.TANZANIA]: [
    Country.BURUNDI,
    Country.RWANDA,
    Country.UGANDA,
    Country.KENYA,
    Country.MALAWI,
    Country.MOZAMBIQUE,
    Country.ZAMBIA,
    Country.DEMOCRATIC_REPUBLIC_OF_CONGO,
  ],
  [Country.SAN_MARINO]: [Country.ITALY],
  [Country.SAO_TOME_AND_PRINCIPE]: [],
  [Country.SEYCHELLES]: [],
  [Country.SENEGAL]: [Country.MAURITANIA, Country.MALI, Country.GUINEA, Country.GUINEA_BISSAU, Country.GAMBIA],
  [Country.SAINT_KITTS_AND_NEVIS]: [],
  [Country.SERBIA]: [
    Country.HUNGARY,
    Country.ROMANIA,
    Country.BULGARIA,
    Country.KOSOVO,
    Country.NORTH_MACEDONIA,
    Country.MONTENEGRO,
    Country.BOSNIA_AND_HERZEGOVINA,
    Country.CROATIA,
  ],
  [Country.SLOVENIA]: [Country.ITALY, Country.AUSTRIA, Country.HUNGARY, Country.CROATIA],
  [Country.SOLOMON_ISLANDS]: [],
  [Country.SUDAN]: [Country.EGYPT, Country.ERITREA, Country.ETHIOPIA, Country.SOUTH_SUDAN, Country.CENTRAL_AFRICAN_REPUBLIC, Country.CHAD, Country.LIBYA],
  [Country.TRINIDAD_AND_TOBAGO]: [],
  [Country.TURKEY]: [Country.BULGARIA, Country.GREECE, Country.SYRIA, Country.IRAQ, Country.IRAN, Country.ARMENIA, Country.GEORGIA],
  [Country.UGANDA]: [Country.SOUTH_SUDAN, Country.KENYA, Country.TANZANIA, Country.RWANDA, Country.DEMOCRATIC_REPUBLIC_OF_CONGO],
  [Country.UZBEKISTAN]: [Country.KAZAKHSTAN, Country.KYRGYZSTAN, Country.TAJIKISTAN, Country.AFGHANISTAN, Country.TURKMENISTAN],
  [Country.URUGUAY]: [Country.ARGENTINA, Country.BRAZIL],
  [Country.FRANCE]: [Country.BELGIUM, Country.LUXEMBOURG, Country.GERMANY, Country.SWITZERLAND, Country.ITALY, Country.MONACO, Country.ANDORRA, Country.SPAIN],
  [Country.CENTRAL_AFRICAN_REPUBLIC]: [
    Country.CHAD,
    Country.SUDAN,
    Country.SOUTH_SUDAN,
    Country.DEMOCRATIC_REPUBLIC_OF_CONGO,
    Country.REPUBLIC_OF_CONGO,
    Country.CAMEROON,
  ],
  [Country.MONTENEGRO]: [Country.CROATIA, Country.BOSNIA_AND_HERZEGOVINA, Country.SERBIA, Country.KOSOVO, Country.ALBANIA],
  [Country.CHILE]: [Country.PERU, Country.BOLIVIA, Country.ARGENTINA],
  [Country.SWITZERLAND]: [Country.FRANCE, Country.GERMANY, Country.AUSTRIA, Country.ITALY, Country.LIECHTENSTEIN],
  [Country.SWEDEN]: [Country.NORWAY, Country.FINLAND],
  [Country.EQUATORIAL_GUINEA]: [Country.CAMEROON, Country.GABON],
  [Country.ETHIOPIA]: [Country.ERITREA, Country.DJIBOUTI, Country.SOMALIA, Country.KENYA, Country.SOUTH_SUDAN, Country.SUDAN],
  [Country.SOUTH_AFRICA]: [Country.NAMIBIA, Country.BOTSWANA, Country.LESOTHO, Country.ZIMBABWE, Country.ESWATINI, Country.MOZAMBIQUE],
  [Country.GAZE]: [Country.ISRAEL, Country.EGYPT],
  [Country.PALESTINE]: [Country.ISRAEL, Country.JORDAN],
  [Country.KOSOVO]: [Country.SERBIA, Country.NORTH_MACEDONIA, Country.ALBANIA, Country.MONTENEGRO],
  [Country.GUAM]: [],
  [Country.NEW_CALEDONIA]: [],
  [Country.TAHITI]: [Country.POLYNESIA],
  [Country.ISLA_DE_PASCUA]: [Country.POLYNESIA],
};

// Проверка что все страны записаны как соседи корректно
{
  Object.entries(COUNTRIES_NEIGHTBOURS).forEach(([country, neighbours]) => {
    neighbours.forEach((neighbour) => {
      if (!COUNTRIES_NEIGHTBOURS[neighbour]) {
        alert('Не найден сосед');
        throw new Error('neighbour' + neighbour + ' of ' + country);
      }
      const isInclude = COUNTRIES_NEIGHTBOURS[neighbour].includes(country as Country);
      if (!isInclude) {
        alert(`Страна ${neighbour} не имеет соседа ${country}`);
      }
    });
  });
}

// Какие моря бывают
// По континентам тест
// Сделать проверку что если один город включает другой, то и другой включает первый
// Игра на вид цветов, грибов и прочее
// Назави страны на букву ...
// Игра отметить острова
// Написать скрипт для проверки, что б все страны взаимно друг друга включали и ничего не упустил
// Игра в угадать направление!
// Сделать так, что б свопросом ещё видел и флаг
// Как пишутся на англ
// Страны на одну букву
// 10 крупных стран, самые крупные страны по континентам
// Выбрать столице
